apiVersion: v1
kind: Service
metadata:
  name: rf2vc
  namespace: rf2vc-system
  labels:
    app: rf2vc
spec:
  selector:
    app: rf2vc
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
